- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes
- name: Install basic packages
  apt: 
    name: "{{ item }}"
    update_cache: true
    state: present
  with_items:
    - build-essential
    - libhdf5-dev
    - libblas-dev
    - liblapack-dev
    - gfortran
    - cython
    - libjpeg8-dev
    - libtiff5-dev
    - libjasper-dev
    - libpng12-dev
    - libdlib-dev
    - cmake
    - pkg-config
    - git
    - htop
    - swig
    - libcurl3-dev 
    - nmap
- name: Install list of python packages
  apt: 
    name: "{{ item }}"
    update_cache: true
    state: present
  with_items:
    - virtualenvwrapper
    - python-dev
    - python-pip
    - python-setuptools
    - python-numpy
    - python-virtualenv
    - python-wheel
    - python3-dev
    - python3-numpy
    - python3-pip
    - python3-setuptools
    - python3-wheel
- name: Install Jupyter Notebook,Matplotlib,boto3 and Tensorflow
  pip: 
   name: "{{ item }}" 
   executable: pip3 
   with_items:
    - jupyter
    - matplotlib
    - boto3
    - tensorflow
- name: Copying Training Script
  template: src=distributed_example_hdfs.py.j2 dest=/home/ubuntu/distributed_example_hdfs.py
- name: Copying advanced template with s3Select
  template: src=distributed_example_s3select.py.j2 dest=/home/ubuntu/distributed_example_s3select.py
- name: Copying script
  template: src=run.sh dest=/home/ubuntu/run.sh
- name: Copying script
  template: src=run_s3.sh dest=/home/ubuntu/run_s3.sh