- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest
- name: Update all packages to the latest version
  apt:
    upgrade: dist
- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes    
- name: Install Python3-dev tools
  apt: pkg=python3-dev state=latest update_cache=yes
- name: Install pip
  apt: pkg=python3-pip state=latest update_cache=yes
- name: Upgrade pip
  pip: 
   name: pip 
   state: latest
   executable: pip3
- name: Install tensorflow
  pip: 
   name: tensorflow 
   extra_args: --ignore-installed six
   become: True
- name: Copying template
  template: src=distributed_example.py.j2 dest=/home/ubuntu/distributed_example.py
