- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes
- name: Install list of basic packages
  apt: 
    name: "{{item}}"
    update_cache: true
    state: present
  with_items:
    -'build-essential'
    -'libhdf5-dev'
    -'libblas-dev'
    -'liblapack-dev'
    -'gfortran'
    -'cython'
    -'libjpeg8-dev'
    -'libtiff5-dev'
    -'libjasper-dev'
    -'libpng12-dev'
    -'libdlib-dev'
    -'cmake'
    -'pkg-config'
    -'git'
    -'htop'
    -'swig'
    -'libcurl3-dev' 
- name: Install list of python packages
  apt: 
    name: "{{item}}"
    update_cache: true
    state: present
  with_items:
    -'virtualenvwrapper'
    -'python-dev'
    -'python-pip'
    -'python-setuptools'
    -'python-numpy'
    -'python-dev'
    -'python-pip'
    -'python-virtualenv'
    -'python-wheel'
    -'python3-dev'
    -'python3-numpy'
    -'python3-pip'
    -'python3-setuptools'
    -'python3-wheel'
- name: Install tensorflow
  pip: 
   name: tensorflow 
   executable: pip3 
- name: Copying template
  template: src=distributed_example.py.j2 dest=/home/ubuntu/distributed_example.py
